=== venkata554/mule-module-absoluterule-examples/mule-module-absoluterule-validation/models/transactions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="transactions" type="Transactions"/>
    <xs:complexType name="Transactions">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="transaction" type="Transaction"/>
            <xs:element name="startBalance" type="xs:decimal"/>
            <xs:element name="endBalance" type="xs:decimal"/>
            <xs:element name="statementDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Transaction">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="amount" type="xs:decimal"/>
            <xs:element name="type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== venkata554/mule-module-absoluterule-examples/mule-module-absoluterule-validation/target/test-classes/valid-instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<transactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transactions.xsd">
    <transaction>
        <date>2011-06-01</date>
        <amount>3000.0</amount>
        <type>PAYMENT</type>
    </transaction>
    <transaction>
        <date>2011-06-03</date>
        <amount>-500.0</amount>
        <type>BANKFEE</type>
    </transaction>    <transaction>
        <date>2011-06-05</date>
        <amount>2500.0</amount>
        <type>PAYMENT</type>
    </transaction>    
    <startBalance>5000.0</startBalance>
    <endBalance>10000.0</endBalance>
    <statementDate>2011-06-07</statementDate>
</transactions>
